/**
 * Generate the ISO 3166-1 lookup used to join our alpha-2 country codes to the
 * world-atlas TopoJSON polygons (which are keyed by NUMERIC codes).
 * Run: npm run iso
 *
 * Emits a compact generated TS module so no JSON-import tsconfig flag is needed.
 */
import { createRequire } from 'node:module'
import { writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const require = createRequire(import.meta.url)
const countries = require('world-countries')

const rows = countries
  .filter((c) => c.cca2 && c.ccn3) // must have both alpha-2 and numeric
  .map((c) => ({ a2: c.cca2, numeric: c.ccn3, name: c.name.common }))
  .sort((a, b) => a.name.localeCompare(b.name))

const out = `// AUTO-GENERATED by scripts/gen-iso.mjs — do not edit by hand.
// ISO 3166-1: alpha-2 <-> numeric <-> common name. Numeric codes match the
// world-atlas TopoJSON feature ids.
export interface IsoCountry {
  a2: string
  numeric: string
  name: string
}

export const ISO_COUNTRIES: IsoCountry[] = ${JSON.stringify(rows, null, 0)}
`

const dest = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'lib', 'isoCountries.data.ts')
await writeFile(dest, out)
console.log(`wrote ${dest} (${rows.length} countries)`)
